/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeImport } from './routes/Home'
import { Route as FavoritesImport } from './routes/Favorites'

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: '/Home',
  path: '/Home',
  getParentRoute: () => rootRoute,
} as any)

const FavoritesRoute = FavoritesImport.update({
  id: '/Favorites',
  path: '/Favorites',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Favorites': {
      id: '/Favorites'
      path: '/Favorites'
      fullPath: '/Favorites'
      preLoaderRoute: typeof FavoritesImport
      parentRoute: typeof rootRoute
    }
    '/Home': {
      id: '/Home'
      path: '/Home'
      fullPath: '/Home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/Favorites': typeof FavoritesRoute
  '/Home': typeof HomeRoute
}

export interface FileRoutesByTo {
  '/Favorites': typeof FavoritesRoute
  '/Home': typeof HomeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/Favorites': typeof FavoritesRoute
  '/Home': typeof HomeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/Favorites' | '/Home'
  fileRoutesByTo: FileRoutesByTo
  to: '/Favorites' | '/Home'
  id: '__root__' | '/Favorites' | '/Home'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
}

const rootRouteChildren: RootRouteChildren = {
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/Favorites",
        "/Home"
      ]
    },
    "/Favorites": {
      "filePath": "Favorites.tsx"
    },
    "/Home": {
      "filePath": "Home.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
